# .ruff.toml

# Какие каталоги проверять
src = ["src"]

# Включаем основные категории ошибок
select = ["E", "F", "I", "B", "C"]
# Игнорируем слишком длинные строки
ignore = ["E501"]
# В тестах не требуем докстринги
per-file-ignores = { "tests/*" = ["D"] }

# Параметры авто-форматирования в стиле Black
line-length = 88
target-version = "py311"
