# Пути к исходникам
src = ["src"]

# Целевая версия Python
target-version = "py311"

# Какие ошибки ловить
select = ["E", "F", "I", "B", "C"]

# Какие ошибки игнорировать
ignore = ["E501"]

# В тестах не требуем докстринги
per-file-ignores = { "tests/*" = ["D"] }
